server:
  port: 8001

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##GREEDY
    password: GREEDY
mybatis:
  mapper-locations: mappers/**/*.xml
